const SET_NAME = 'SET_NAME';
const SET_STATUS = 'SET_LAST_WIN';
const SET_CHOICE = 'SET_CHOICE';
const ADD_PHRASE = 'ADD_PHRASE';
const RESET = 'RESET';

export { SET_NAME, SET_STATUS, SET_CHOICE, ADD_PHRASE, RESET };